### ISSUE TITLE
callback with optional parameters do not generate nullable parameters

### ISSUE THREAD

**Issue by itsramiel** [mrousavy/nitro#142] opened 2024-09-19 14:24 UTC
I have the following function:
```ts
pickFileCb(cb: (filepath: string | null) => void): void
```

but the generated swift methods is:
```swift
  func pickFileCb(cb: @escaping ((_ filepath: String) -> Void)) throws -> Void
```

I also tried `filepth: string | undefined` and `filepath?: string` and all doesnt work.

Note that it works with promises, so:
```ts
pickFileAsync(): Promise<string | null>
``` 
produces
```swift
  func pickFileAsync() throws -> Promise<String?>
```

**Comment by mrousavy** [comment] 2024-09-23 09:07
Thanks for reporting, but this is a duplicate of https://github.com/mrousavy/nitro/issues/20

**Closed by mrousavy** 2024-09-23 09:07 UTC
